services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\FormExtended\:
    resource: '../Classes/*'


  WapplerSystems\FormExtended\EventListener\DataStructureIdentifierListener:
    tags:
      - name: event.listener
        identifier: 'form-extended/modify-data-structure'
        method: 'modifyDataStructure'
